### ISSUE TITLE
CORS error in /metaplex/upload

### ISSUE THREAD

**Issue by kevinfaveri** [nftstorage/metaplex-auth#5]
I'm getting a /metaplex/upload CORS error from localhost when running this lib in the browser

![Screen Shot 2021-11-29 at 7 11 13 PM](https://user-images.githubusercontent.com/18222497/143950869-23173fed-b41a-4559-a909-a9e183a8aa7d.png)

Is this by design on nft.storage?

**Comment by yusefnapora** [comment]
I think that's happening because the endpoint doesn't exist on the production API yet, just staging. So when you make an `NFTStorageUploader` you need to pass in an endpoint URL:

```
const auth = MetaplexAuthWithSigner(...)

const uploader = new NFTStorageUploader(auth, 'https://api-staging.nft.storage)
```

Sorry about the lack of docs - I'm hoping to fix that this week.
